name: GitHub Actions Demo
on:
  push:
    branches: main
    paths-ignore: .github/**
  pull_request:
    branches: main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: echo "event name is ${{ github.event_name }}"
      - run: echo "branch name is ${{ github.ref }}"
      - run: tree 
  
