name: CI Build for Docker Action
on:
  push:
    branches: main
    paths: hello-world-docker-action/**
  workflow_dispatch:
    
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: zevanreg/hello-world-docker-action@v1.1
        id: hello
        with:
          who-to-greet: ${{ github.actor }}
      - run: echo "Action ran on ${{ steps.hello.outputs.time }} "
