name: Reuse other workflow
on: [workflow_dispatch]

jobs:
  call-workflow:
    uses: zevanreg/actionsfundamentals/.github/workflows/reusable.yml@main
    with:
      who-to-greet: ${{ github.actor }}

  use-output:
    needs: call-workflow
    runs-on: ubuntu-latest
    steps:
      - run: ${{ needs.call-workflow.outputs.current-time }}
